### PR TITLE
 Task#10 Fix - Button filters

### LINKED ISSUE #66: Feature: Includes filters to help customers choose the product they want
- [x] #67

> As a user, at the app, I can see the "price" button in the header. When I click on the "price" button, just below the button appears a screen with a list price range of the product so i can choose the price that suits your requirements.

- [x] #70

### LINKED ISSUE #70: Bug: Missing UI, wrong Ux, showing list from wrong filters
- [x] #71

### LINKED ISSUE #71: Task#10 DevTask - Fix bug for filters
-  #66 

## OVERVIEW

- Error: Show all or not display the product list when using filter
- Error: No or dynamic price filter
- Error: Failed to synchronize with filter buttons with the same function
- Error: UI - User can't tell if filter is selected or not

### NOTE
- If user want to see all products, user need reload app.

### PR DESCRIPTION
**Pull request by TheHienDuong**
- FIxed #71 
## OVERIVEW

> Error: Show all or not display the product list when using filter
> Error: No price filter
> Error: Duplicate prodcuts
> Error: Failed to synchronize with filter buttons with the same function
> Error: UI - User can't tell if filter is selected or not

## SOLUTION
- Using variable displayProducts to save filter from logo to browse through price then render
      - Instead of using a loop to filter which filters are selected and then display the products, use that loop to store the names of the filters, then use a function to perform the product update function
- Update the same buttons for the necessary filters
- Edit prodcuts.json, remove duplicate products
- Use sameLogoButtons,samePriceButtons to synchronize buttons with the same function
- Add effects and border for button logos to update changes.

## DEMO

https://github.com/Agility-Internship/Duong-The-Hien-Javascript/assets/113186169/95f1433e-025e-48b4-a4a4-b7017f044784

### CODE REVIEW

File: practice-02/js/index.js [hunk 1]
```diff
@@ -1,13 +1,55 @@
...
  * @param products: data is passed from products.json file with type json
  * @param name: the value of the name tag passed in the argument
  * @returns {Array} An array of filtered products
  */
-function filterProductsByName(products, name) {
-    return products.filter(product => product.name.toLowerCase().includes(name.toLowerCase()));
+function filterProductsByName(products, selectedBrands) {
+    const filteredResults = [];
+
+    console.log(selectedBrands)
```
Comment (phattruong-agilityio) [inline practice-02/js/index.js]: remove console.log

File: practice-02/js/index.js [hunk 2]
```diff
@@ -1,13 +1,55 @@
...
+    selectedBrands.forEach(brand => {
+        console.log(brand)
```
Comment (phattruong-agilityio) [inline practice-02/js/index.js]: remove console
